### ISSUE TITLE
TypeError: printer.list is not a function in version 1.4.1

### ISSUE THREAD

**Issue by MilburnGomes** [artiebits/pdf-to-printer#185]
I tried to recreate your express-server example. But when I installed pdf-to-printer, it installed to the latest version. On hitting http://localhost:8080/list, I get the below error:
TypeError: printer.list is not a function
    at list (C:\Users\DELL\Desktop\print-app-node\src\list.js:13:6)
    at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\Users\DELL\Desktop\print-app-node\node_modules\body-parser\lib\types\json.js:110:7)
    at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\print-app-node\node_modules\express\lib\router\layer.js:95:5)

However, if I revert to the version used in the example (i.e. version 1.1.1) it works fine.

**Comment by artiebits** [comment]
Hi @MilburnGomes, thanks for letting me know about the issue. `.list()` was renamed to `.getPrinters()` but I forgot to update examples. So, if you are using 1.4.1, try `getPrinters()`.
If you are interested in contributing - feel free to open a PR with updating examples, I would appreciate it.
Let me know If it helps you!

**Comment by MilburnGomes** [comment]
> 
> 
> Hi @MilburnGomes, thanks for letting me know about the issue. `.list()` was renamed to `.getPrinters()` but I forgot to update examples. So, if you are using 1.4.1, try `getPrinters()`.
> If you are interested in contributing - feel free to open a PR with updating examples, I would appreciate it.
> Let me know If it helps you!

Thanks a lot for your prompt reply and support! I've made the change it works great!
